# Generated by Django 4.2.7 on 2023-11-29 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_jobsearcherprofile'),
        ('common', '0002_driverlicense_education_experience_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.jobsearcherprofile'),
        ),
        migrations.AddField(
            model_name='language',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.languagedegree'),
        ),
        migrations.AddField(
            model_name='language',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.languagetype'),
        ),
        migrations.AddField(
            model_name='language',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.jobsearcherprofile'),
        ),
        migrations.AddField(
            model_name='experience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.jobsearcherprofile'),
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.jobsearcherprofile'),
        ),
    ]
