# Generated by Django 4.2.7 on 2023-11-30 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_jobsearcherprofile_currency_and_more'),
        ('common', '0003_socialmedia_user_language_degree_language_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='user.jobsearcherprofile'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='user.jobsearcherprofile'),
        ),
        migrations.AlterField(
            model_name='language',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='user.jobsearcherprofile'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_medias', to='user.jobsearcherprofile'),
        ),
    ]
