# Generated by Django 4.2.7 on 2023-11-29 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_driverlicense_education_experience_language_and_more'),
        ('user', '0002_companyprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSearcherProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Erkak', 'Male'), ('Ayol', 'Female')], max_length=255)),
                ('bithed_date', models.DateField()),
                ('about', models.TextField()),
                ('salary', models.IntegerField()),
                ('currency', models.CharField(choices=[('UZS', 'Uzs'), ('USD', 'Usd')], default='UZS', max_length=20)),
                ('is_freelancer', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.activity')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.district')),
                ('driver_license', models.ManyToManyField(to='common.driverlicense')),
                ('skills', models.ManyToManyField(to='common.skill')),
            ],
            options={
                'abstract': False,
            },
            bases=('user.user', models.Model),
        ),
    ]
