# Generated by Django 4.2.7 on 2023-11-30 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_jobsearcherprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsearcherprofile',
            name='currency',
            field=models.CharField(choices=[('UZS', 'Uzs'), ('USD', 'Usd')], default='UZS', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqamingiz 9 bilan boshlanishi va 12 ta belgidan iborat bo'lishi kerak. Masalan: 998901235476", regex='^998[0-9]{9}$')]),
        ),
    ]
