# Generated by Django 4.2.7 on 2023-11-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_jobsearcherprofile_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsearcherprofile',
            name='currency',
            field=models.CharField(choices=[('UZS', 'Uzs'), ('USD', 'Usd')], default='UZS', max_length=20),
        ),
    ]
