# Generated by Django 4.2.7 on 2023-11-30 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_education_user_alter_experience_user_and_more'),
        ('user', '0005_alter_jobsearcherprofile_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsearcherprofile',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.activity'),
        ),
        migrations.AlterField(
            model_name='jobsearcherprofile',
            name='currency',
            field=models.CharField(choices=[('UZS', 'Uzs'), ('USD', 'Usd')], default='UZS', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobsearcherprofile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.district'),
        ),
        migrations.AlterField(
            model_name='jobsearcherprofile',
            name='driver_license',
            field=models.ManyToManyField(blank=True, to='common.driverlicense'),
        ),
        migrations.AlterField(
            model_name='jobsearcherprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='common.skill'),
        ),
    ]
